### ISSUE TITLE
Implementar: Select / Dropbox / Tooltip

### ISSUE THREAD

**Issue by guidiego** [opensanca/burro#10]
A ideia é fazer um Dropbox similar ao do FlatUI:

<img width="251" alt="captura de tela 2018-07-05 as 18 17 57" src="https://user-images.githubusercontent.com/10289071/42348555-3ab233b8-8080-11e8-9254-17405d032031.png">

A diferença é que o input não fique esse verde estranho e sim algo mais similar ao input tradicional:
https://github.com/opensanca/burro/issues/6

### Tooltip
Perceba que é um componente muito similar e podemos reaproveitar e ja criar no mesmo PR :)

<img width="241" alt="captura de tela 2018-07-05 as 18 21 16" src="https://user-images.githubusercontent.com/10289071/42348556-3ad8b6be-8080-11e8-9d3d-656262ae4eb2.png">

## ATENÇÃO
No mobile, fazer o dropdown oculpar a tela inteira com um `position: fixed` e se ajustar com `transform` ;)

**Comment by cristofersousa** [comment]
Não seria melhor separar cada component por issue á parte? 

```
- Create Component Tooltip
- Create Component Select
- Create Component Dropbox
```
